# Application
spring.application.name=property-portal

# Context path (important for Tomcat WAR)
# server.servlet.context-path=/property-portal
#server.servlet.context-path=/

# Logging (minimal)
logging.level.root=INFO

# Disable DB auto config (for simple deploy)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
